import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingActions from "./com/floatingicon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* 
           MAIN WRAPPER 
           - Removed max-w and mx-auto to allow full edge-to-edge width
           - Removed px padding to ensure content touches the screen edges
        */}
        <main className="flex-grow w-full">
          {children}
        </main>

        {/* Floating actions stay outside main to avoid layout shifts */}
        <FloatingActions />
      </body>
    </html>
  );
}